### PR TITLE
Fix an error in advanced types example

### PR DESCRIPTION
**Pull request by zhongsp**
Fix an error in code sample.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Nice catch! Though, I wonder if this is just confusing. @sandersn @mhegazy, do you two have any thoughts on this?

**Comment by sandersn** [comment]
Yes, it's confusing. Union types are already discussed above, so I'd just delete everything in the code block from `type XYZCoord` and below.

**Comment by sandersn** [comment]
The union example is not useful in addition -- it's a jumble of types that's really hard to distinguish with a type guard, at least without some kind of type tag which doesn't work well at the moment.

**Comment by zhongsp** [comment]
@DanielRosenwasser The update in PR 138 is more clear. I think we could close this PR. :smile:

**Comment by mhegazy** [comment]
thanks @zhongsp!

**Pull request closed without merging**
