### PR TITLE
Update: React tutorial Jest example

### PR DESCRIPTION
**Pull request by A1vinSmith**
Updated the usage of Jest in React tutorial

1. Add the correct installation of Jest
2. Fix the missing of necessary adapter of enzyme
3. Update react-addons-test-utils applicable conditions

### CODE REVIEW

**Comment by mhegazy** [comment]
@DanielRosenwasser can you please review?

**Comment by foyangyu** [comment]
@DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Sorry about that! Hey @foyangyu, this page is actually hosted on https://github.com/Microsoft/TypeScript-React-Starter. Would you be able to port the changes to that page instead? I'm sorry about the delay.

**Comment by foyangyu** [comment]
@DanielRosenwasser Good to know, thank you.

**Pull request closed without merging**
