### PR TITLE
Remove confusing alias example

### PR DESCRIPTION
**Pull request by sandersn**
Union types are already explained, and the types that are aliased are next to impossible to distinguish with a type guard to boot.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I'd prefer we actually showed an example where we show something that has the type of an alias, so I don't think removing it entirely is the right move. Using different names would be more optimal.

**Comment by sandersn** [comment]
A value of the aliased type, right? I'll put one back in, just not a value of a union type.

**Comment by DanielRosenwasser** [comment]
That's better, but we now need something to show a type alias for a union.

**Comment by sandersn** [comment]
Why? They are orthogonal concepts and showing that they work together just makes the explanation over-complicated.

**Comment by mhegazy** [comment]
what is the status of this PR? 
I think there is value in showing that type aliases can alias unions, intersection, and arrays. may be add a function that accepts an array of Coordinates defined as a type alias.

**Comment by sandersn** [comment]
Here's the example I came up with

```ts
type Coord = XCoord | YCoord | XYCoord;
function distance(c: Coord): number {
    if (typeof c === 'number') {
        return c;
    }
    else {
        return Math.sqrt(Math.pow(c.x, 2) + Math.pow(c.y, 2));
    }
}
```

It's still a bit wonky because XCoord and YCoord are really the same type, and writing other functions for this (or similar data structures) would break down pretty fast. For example:

```
// how to distinguish X from Y?
declare function xComponent(c: Coord): number;
// how to distinguish XY from Polar?
type PolarCoord = { angle: number, radius: number }
type Coord = X | Y | XY | Polar;
```

So it's not quite a real example still.

**Comment by mhegazy** [comment]
how about `string | (()=> string)`, something like 

```ts
type Name = string;
type NameResolver = ()=> Name;
type NameOrNameResolver = Name | NameResolver;

function getName(n: NameOrNameResolver): Name {
    if (typeof n === "string") {
      return n;
   }
   else {
      return n();
   }
}
```

**Comment by sandersn** [comment]
Good idea. I like the Name example better.

**Comment by mhegazy** [comment]
:+1:

**Pull request merged**
