### PR TITLE
Noting example is below text and not above.

### PR DESCRIPTION
**Pull request by GrizzlyMcBear**
Fixes #

### CODE REVIEW

**Comment by mhegazy** [comment]
The original text seems accurate. it refers to the example above. what makes you believe it should refer to the following example instead?

**Comment by DanielRosenwasser** [comment]
Yeah, but now that I look at it, I wonder what the below example is actually trying to show. Maybe that should be improved.

**Comment by GrizzlyMcBear** [comment]
@mhegazy I thought the same at first, but after reading the second example
I saw that it had no description and also that the description seemed more relevant to it
instead of to the first example.

**Comment by RyanCavanaugh** [comment]
Thank you for helping contribute to the TypeScript Handbook! We're trying to get through the large backlog of open PRs. As part of that effort, we're only merging PRs that *clearly improve* the content. PRs that only change phrasing, style, nits, or other aspects not directly related to accuracy or coverage won't be accepted - this will greatly reduce merge conflicts in PRs that do have content-critical changes. We'll be closing PRs like this one that make subjective improvements; often given two ways of writing the same thing, opinion will be split on which is better, and we have to defer to making fewer changes rather than more. Thanks for understanding.

**Pull request closed without merging**
