### PR TITLE
Added table of contents

### PR DESCRIPTION
**Pull request by danmarshall**
Table of contents is helpful to see the complete list of tools at a glance, otherwise this could be construed as a "Browserify only" page.

### CODE REVIEW

**Comment by mhegazy** [comment]
no clue why the CI is barfing here. need to investigate.

**Comment by danmarshall** [comment]
@mhegazy fixed!

**Comment by mhegazy** [comment]
not sure what is going on..
image

**Comment by danmarshall** [comment]
Just a minute - I needed to update branch.

**Comment by danmarshall** [comment]
@mhegazy 👍

**Comment by mhegazy** [comment]
yaay! thanks.

**Comment by danmarshall** [comment]
@mhegazy how often do you build / deploy the Handbook?

**Comment by mhegazy** [comment]
nothing regular. i do it on demand kinda thing or when we are ready to push a new version out.

**Pull request merged**
