### PR TITLE
page(Advanced Types): update code sample

### PR DESCRIPTION
**Pull request by NicBright**
Fixes #

Type assertion is not necessary here. It only increases noise and makes the example more difficult to read.

### CODE REVIEW

**Comment by mhegazy** [comment]
With this change the sample will throw errors under `--noImplicitAny` flag. it is a goal to make sure all samples compile with no errors under `--noImplicitAny`.

**Comment by NicBright** [comment]
> it is a goal to make sure all samples compile with no errors under --noImplicitAny

Ok. But why do you have this goal? Shouldn't the goal be to make the best possible documentation? Increasing strictness on the examples doesn't help for that goal.

**Comment by mhegazy** [comment]
it is confusing when ppl copy a sample and it does not work for them. so we are trying to avoid that too. 

the type assertions are part of the language. so i am not sure i see the two objectives contradicting.

**Comment by RyanCavanaugh** [comment]
Thank you for helping contribute to the TypeScript Handbook! We're trying to get through the large backlog of open PRs. As part of that effort, we're only merging PRs that *clearly improve* the content. PRs that only change phrasing, style, nits, or other aspects not directly related to accuracy or coverage won't be accepted - this will greatly reduce merge conflicts in PRs that do have content-critical changes. We'll be closing PRs like this one that make subjective improvements; often given two ways of writing the same thing, opinion will be split on which is better, and we have to defer to making fewer changes rather than more. Thanks for understanding.

**Pull request closed without merging**
