### PR TITLE
Basic Types: refine template string code sample.

### PR DESCRIPTION
**Pull request by weakish**
Replace unnecessary usage of template string with regular string.

---
 pages/Basic Types.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

### CODE REVIEW

**Comment by mhegazy** [comment]
why is it unnecessary? template strings are allowed to have no substitution spans, and this can be used in place of any string literal.

**Comment by mhegazy** [comment]
this example is intentional. so do not think this PR is needed.

**Comment by weakish** [comment]
@mhegazy  If it is intentional, I recommend comment it explicitly. 
Using template string to represent normal string is not preferred, since it gives reader false expectation
(a reader may think there is some interpolation  within the string). Thus it wastes reader's time if the string is long.

**Comment by mhegazy** [comment]
> Using template string to represent normal string is not preferred, since it gives reader false expectation

Why? it is an ES6 feature, and a valid JS literal expression, see http://www.ecma-international.org/ecma-262/6.0/#sec-template-literals

**Pull request closed without merging**
