### PR TITLE
fix Class doc: update Greeter to greeter

### PR DESCRIPTION
**Pull request by bmeritter**
Fixes #

### CODE REVIEW

**Comment by orta** [comment]
I think (though it does feel ambiguous) that this sentence refers to the first line in the code sample which means this fix is probably wrong. So I'll close this - thanks for giving an improvement a shot! It means a lot when folks help improve the core docs :D

**Comment by bmeritter** [comment]
@orta  I just think Greeter is a Class, but greeter is an object, greeter is an instance of Greeter. We should let it clear.

**Comment by orta** [comment]
Sure if you want to rename the instance in the docs that could help?

**Comment by bmeritter** [comment]
@orta Yeah

**Pull request closed without merging**
