### PR TITLE
Add readonly for React Props interface

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**
see https://reactjs.org/docs/components-and-props.html#props-are-read-only

### CODE REVIEW

**Comment by orta** [comment]
Yeah, that seems like a good call 👍

**Comment by sw-yx** [comment]
fwiw i think a year ago @ferdaber said that the readonly is going to be applied from the `@types/react` side - not sure if that actually happened

**Comment by ferdaber** [comment]
For class components I believe they are already read only.

**Comment by xiaoxiangmoe** [comment]
For function component, readonly is needed.

What should I do now?

**Comment by ferdaber** [comment]
this PR is probably fine as-is, the updates on the React typings side can come later.

**Comment by orta** [comment]
I'm not merging any PRs on this repo (content is frozen in preparation for archiving - see #1313) but when we flip the switch, I'll port over PRs to the v2 site

So for now, you can do nothing

**Comment by orta** [comment]
These two tutorials now redirect to the typescript pages on the tool's side - so I can't reapply any of this to the v2 site. Thanks for the PR though!

**Pull request closed without merging**
