### PR TITLE
Document readonly

### LINKED ISSUE #311: Add documentation readonly properties and index signatures

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #311

### CODE REVIEW

**Comment by mhegazy** [comment]
can you also add a note about getters with no setters are inferred to be readonly properties.

**Comment by mhegazy** [comment]
👍

**Comment by sandersn** [comment]
I thought about adding that note, but I'm not sure what difference it makes? Just in the .d.ts, right?

**Comment by mhegazy** [comment]
for usage as well. 

```ts
class C {
    get x() { return 0; }
}
c.x = 1; // Error
```

**Comment by sandersn** [comment]
Right, but `readonly` doesn't add anything that wasn't there before. The only change is in the type. I'll make the note.

**Comment by mhegazy** [comment]
might not be worth it... up to you.

**Comment by sandersn** [comment]
I went ahead with it. I didn't think about the `.d.ts` case when I first made the decision not to document it.

**Comment by mhegazy** [comment]
👍

**Pull request merged**
