### PR TITLE
Fixes 'keyof T' type example

### PR DESCRIPTION
**Pull request by aleph-naught2tog**
Fixes #29249 from the TypeScript repository

### CODE REVIEW

**Comment by guillaumep** [comment]
@aleph-naught2tog Actually TypeScript returns `(string | number)[]` and not `string[]`.

This atypical result would certainly require some explanation (it confuses me a lot).

**Comment by aleph-naught2tog** [comment]
@DanielRosenwasser I think I'm confused; which is the _correct_ typing then? I had read the issue as being that it _wasn't_ `string[]` so the fix was to make it that, but I can totally change it 😁

**Comment by RyanCavanaugh** [comment]
Thank you for contributing to the TypeScript Handbook!

We are currently working through a large backlog of open PRs. As part of this, we're asking authors of PRs with active merge conflicts to assess if their changes are still needed, and if so, open a new PR.

For transparency, we are also working on a full-scale reimagining of the Handbook (see the [TypeScript Roadmap](https://github.com/Microsoft/TypeScript/issues/29288)), meaning we are largely closing down work on the current version of the Handbook. Typo fixes are always appreciated, but any new content should likely wait until the new Handbook is available so that it can be more naturally adapted to that format.

**Comment by tommck** [comment]
So... it's been 5 months... still not updating the old content?  Do we have an ETA on the new handbook?

**Comment by orta** [comment]
I just merged a PR like this, so the fix will appear in the new site on the next deploy

**Pull request closed without merging**
