### PR TITLE
Added introduction and "Why TS" page

### LINKED ISSUE #67: Have a "Why TypeScript?" section

### PR DESCRIPTION
**Pull request by crutchcorn**
Fixes #67 

I totally understand how important this one is to get right and welcome ANY/all feedback/critisisms. I think I have the most questions about including the last section about typing information (because of it's advanced nature), but I typically use the argument the most when discussing why Typescript should be used in the backend with engineers using ORMs.

Many thanks to @evelynhathaway for taking a look at this once or twice and fixing some errors in it, along with @wavebeem for giving some feedback before pushing up

### CODE REVIEW

**Comment by crutchcorn** [comment]
I know there's been a lot of rework on the docs recently and a heavy push for improving the docs, but not much in terms of an introductory explaination similar to "Why TS". I was wondering what the status of that was, whether it be this PR or something else - I'd love to have an official resource to point towards as more and more look towards TypeScript. 

Is there anything I can do to help with this further? Anything in the PR that might cause problems or have differing opinions? I don't mind rewriting anything if it might help, but also would love to point towards a resource if it came from outside of this PR as well

Tagging reviewer @RyanCavanaugh

**Comment by orta** [comment]
Yeah, this docs gap was why I ended up writing my own too - https://artsy.github.io/blog/2019/04/05/omakase-typescript/

With the specific aim of getting something like this inside the official docs once I was in the team, which I now am. Will talk to folks about this tomorrow, there's a reasonable chance _this_ won't get merged as is - mainly because it lives in the handbook and something like this should probably live in the website itself, but I dig that this is closed source which makes that an impossible contribution.

**Comment by crutchcorn** [comment]
Oh, is the handbook not pulled into the site itself? I didn't realize they were distinct items, I thought the site was a wrapper around the handbook 😅 

All the same, as I mentioned before, no worries about _this_ being merged in, I'd just love to have an official place to point for this stuff (plus, y'all would know much MUCH much more than I in regards to what TS' vision, goals, and pros/cons are)

**Comment by crutchcorn** [comment]
@orta had you had a chance to talk with anyone about this PR? I know the site is now on GitHub:

https://github.com/microsoft/TypeScript-Website

Is this a contribution that might be accepted there? Is there official work being done on a similar page?

**Comment by crutchcorn** [comment]
@orta I'm hoping to get a feel for what the status on this PR is. I want to make sure to give first right (and not violate the code CLA) to Microsoft and hopefully help the community but am also working on a TypeScript series on my open-source CS education blog. I'm wondering if this PR can migrate to where it might be of more use, or if the team has decided they don't want to use this content if I'm able to use it as a starting point for my TypeScript series

**Comment by orta** [comment]
I'd use it on yours - it'll be a while before there's a space on the website for it to fit and I'm loath to expand the definition of the handbook and have to support these links for a long time 👍

**Comment by crutchcorn** [comment]
I totally understand. Thanks a ton for the feedback and heads up :) I'll be moving it to https://github.com/unicorn-utterances/unicorn-utterances with some content changes to match the tone a bit better

**Comment by orta** [comment]
That logo is great!

**Comment by crutchcorn** [comment]
I think so too! @zavukodlak is so darned talented 😁

**Pull request closed without merging**
