### PR TITLE
New page for Utility Types.

### LINKED ISSUE #649: Document `ThisType<T>`
Document the `ThisType<T>` marker interface that can be included (via intersection) in the contextual type of an object literal to set the type of `this` for methods defined in the object literal.  It doesn't seem to be documented anywhere but the [pull request description](https://github.com/Microsoft/TypeScript/pull/14141).

I'll propose text if I have a chance (not right now).

### LINKED ISSUE #798: Document Utility Types (Predefined types)
Opening this issue in response to https://github.com/Microsoft/TypeScript/issues/24558. 

I am currently working on a PR to add a new page to the Handbook titled **Utility Types** (open to suggestions on the title & location of this documentation).

Note that **Utility Types** is a natural name for these utilities as it's the name [adopted by Flow](https://flow.org/en/docs/types/utilities/), and more importantly, it's the terminology originally used in the [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#partial-readonly-record-and-pick) for TS 2.1 to describe several of these utilities.

This PR will document the utility types below:

- [ ] `Partial<T>`
- [ ] `Readonly<T>`
- [ ] `Record<K, T>`
- [ ] `Pick<T, K>`
- [ ] `Exclude<T, U>`
- [ ] `Extract<T, U>`
- [ ] `NonNullable<T>`
- [ ] `ReturnType<T>`
- [ ] `InstanceType<T>`
- [ ] `Required<T>`
- [ ] `ThisType<T>` (would resolve #649)

Feedback appreciated!

### PR DESCRIPTION
**Pull request by chrissantos1995**
Fixes #798

This PR introduces documentation for TypeScript **Utility Types**. 

The majority of the sample code was either borrowed or inspired by the release notes of [TS 2.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html) and [TS 2.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html), and the sample code for `ThisType<T>` was taken from [the PR](https://github.com/Microsoft/TypeScript/pull/14141) that introduced this functionality. 

The documented Utility Types are:

- [x] `Partial<T>`
- [x] `Readonly<T>`
- [x] `Record<K, T>`
- [x] `Pick<T, K>`
- [x] `Exclude<T, U>`
- [x] `Extract<T, U>`
- [x] `NonNullable<T>`
- [x] `ReturnType<T>`
- [x] `InstanceType<T>`
- [x] `Required<T>`
- [x] `ThisType<T>` (fixes #649)

### CODE REVIEW

**Comment by chrissantos1995** [comment]
Hey guys @RyanCavanaugh @DanielRosenwasser -- would love to get some eyes on this 🙏

**Comment by RyanCavanaugh** [comment]
Thank you!

**Comment by Retsam** [comment]
Should this page be published to the website?  I don't see it linked from the "Handbook" sidebar on the main typescript website.

**Comment by mweststrate** [comment]
It is not linked indeed, but can found under: https://www.typescriptlang.org/docs/handbook/utility-types.html

**Pull request merged**
