### PR TITLE
Update webpack.config.js

### PR DESCRIPTION
**Pull request by StephenCleary**
Current version of webpack (2.2.1) does not work with the old configuration. No existing issue, sorry, but it's trivially reproducible (just follow the steps in the article).

### CODE REVIEW

**Comment by mhegazy** [comment]
// CC @DanielRosenwasser

**Comment by seivan** [comment]
@StephenCleary You sure`awesome-typescript-loader` still works? I tried it earlier and I had to change to `ts-loader` instead. 

Another change necessary for getting `RxJs` to work was to change the `target` in `tsconfig.json` :
`"target": "es6"`

**Comment by StephenCleary** [comment]
@seivan [works fine for me](https://github.com/StephenClearyApps/pcltargets/blob/61c55b6c544faf984b12b89f9aa40964bcea7448/webpack.config.js).

**Comment by seivan** [comment]
@StephenCleary Awesome, I'll give it another go! 👍

**Comment by DanielRosenwasser** [comment]
Sorry for the long turnaround and thank you!

**Pull request merged**
