### PR TITLE
fix Decorators page, parameter part code can't run

### PR DESCRIPTION
**Pull request by xsilen**
Fixes # Decorators page, Parameter Decorators
run invoke `Reflect.defineMetadata(requiredMetadataKey, true, target, parameterIndex);` and `Reflect.getOwnMetadata(requiredMetadataKey, method, parameterIndex)`

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@xsilen can you sync with `master`?

**Comment by xsilen** [comment]
updated

**Comment by xsilen** [comment]
same to #174 , my pull request use `map` which is included in es6. #174 is more better.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
@xsilen, can you update with merge conflicts resolved.

**Comment by xsilen** [comment]
closed

**Pull request closed without merging**
