### PR TITLE
Adds Introduced field to Compiler Options

### LINKED ISSUE #298: [Suggestion] Add a Introduced Field to Compiler Options
Compiler Options is getting rather complex and for people coming to TypeScript, when the flag is documented prior to the GA of a release, are getting confused, thinking they can use something they can't.  (Even those of us who are familiar can often forget).  Adding a column that documents in what version it was introduced would help clarity (or add it to the comments).

### PR DESCRIPTION
**Pull request by zspitz**
Fixes #298

### CODE REVIEW

**Comment by mhegazy** [comment]
thanks! can you refresh the PR?

**Comment by zspitz** [comment]
@mhegazy I'm still rather new to Git/Github; how do I do this?

**Comment by mhegazy** [comment]
merge master into your branch again, there should be some conflicts that you need to address, then push again to this branch.

**Comment by mhegazy** [comment]
you want to merge `master` and not `release-2.0`

**Comment by zspitz** [comment]
@mhegazy Finally did this.

**Comment by RyanCavanaugh** [comment]
Thank you for contributing to the TypeScript Handbook!

We are currently working through a large backlog of open PRs. As part of this, we're asking authors of PRs with active merge conflicts to assess if their changes are still needed, and if so, open a new PR.

For transparency, we are also working on a full-scale reimagining of the Handbook (see the [TypeScript Roadmap](https://github.com/Microsoft/TypeScript/issues/29288)), meaning we are largely closing down work on the current version of the Handbook. Typo fixes are always appreciated, but any new content should likely wait until the new Handbook is available so that it can be more naturally adapted to that format.

**Pull request closed without merging**
